### ISSUE TITLE
minimum iOS support version

### ISSUE THREAD

**Issue by iShawnWang** [isavynskyi/LayoutInspector#20]
For my project
It's `platform :ios, '9.0'` in podfile
I want to install and enable this library on iOS 11 +, is there any way ?

**Comment by isavynskyi** [comment]
@iShawnWang, LayoutInspector's minimum deployment target is iOS 11.0
To enable this library on a project with minimum deployment target iOS 9 using CocoaPods:
1. Fork this repo
2. Set `s.ios.deployment_target = '9.0'` in `LayoutInspector.podspec` 
3. Point `LayoutInspector` in your Podfile to the forked branch ([example](https://stackoverflow.com/a/20937937))
4. Then, you will have to fix errors due to some APIs unavailability in iOS 9, one of them will be `UIGraphicsImageRenderer` which is available only since iOS 10.
 
Alternatively, you can manually add `LayoutInspector` to your project and jump straight to the step #4 described above

**Comment by iShawnWang** [comment]
The deployment target is `iOS 13` now, and i want to support from `iOS 9 ` ~ `iOS 13`

**Comment by isavynskyi** [comment]
ok, so you should try steps described above
